### ISSUE TITLE
Is this package published?

### ISSUE THREAD

**Issue by jankapunkt** [imajus/autoform-bootstrap4#1]
I tried to add the package but got 

```
error: unknown package in top-level dependencies: imajus:autoform-bootstrap4
```

On [atmosphere](https://atmospherejs.com/?q=%20imajus%3Aautoform-bootstrap4) there is no package present.

Is there something preventing you from publishing this package?

**Comment by imajus** [comment]
Yes it's still unpublished as it's not fully converted yet. I've only converted components I needed for one of my project. 
But I'll publish package in a few minutes anyway. If someone would want to use components which are not yet supported, she could just send me the PR to accept.

**Comment by imajus** [comment]
Published, you should be able to install the package using `meteor add imajus:autoform-bootstrap4` now.

**Comment by jankapunkt** [comment]
Great, thank you. If I will find issues I will open a PR.
